name: Send Slack Notification With PR Info

on:
  workflow_call:
    inputs:
      user:
        required: false
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: "{\"title\":\"${{github.event.pull_request.title}}\",\"body\":\"${{github.event.inputs.body}}\",\"url\":\"${{github.event.pull_request.html_url}}\",\"user\":\"${{github.event.pull_request.user.login}}\"}"
        env:
          SLACK_WEBHOOK_URL: "https://hooks.slack.com/workflows/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"
